---
permalink: protect-scc/reference_prerequisites_to_adding_hosts_and_installing_snapcenter_custom_plug_ins.html 
sidebar: sidebar 
keywords: credentials 
summary: Bevor Sie einen Host hinzufügen und die Plug-ins-Pakete installieren, müssen Sie alle Anforderungen erfüllen. Die benutzerdefinierten Plug-ins können sowohl in Windows- als auch in Linux-Umgebungen verwendet werden. 
---
= Voraussetzungen für das Hinzufügen von Hosts und die Installation benutzerdefinierter SnapCenter Plug-ins
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Bevor Sie einen Host hinzufügen und die Plug-ins-Pakete installieren, müssen Sie alle Anforderungen erfüllen. Die benutzerdefinierten Plug-ins können sowohl in Windows- als auch in Linux-Umgebungen verwendet werden.

* Sie müssen ein benutzerdefiniertes Plug-in erstellt haben. Weitere Informationen finden Sie in den Entwicklerinformationen.
+
link:concept_develop_a_plug_in_for_your_application.html["Entwickeln Sie ein Plug-in für Ihre Applikation"]

* Wenn Sie MySQL oder DB2 Applikationen managen möchten, müssen Sie die benutzerdefinierten Plug-ins für MySQL und DB2 von NetApp heruntergeladen haben.
* Sie müssen Java 1.8, 64-Bit auf Ihrem Linux- oder Windows-Host installiert haben.
* Wenn Sie ein Plug-in auf einem Windows-Host installieren, wenn Sie keine Anmeldedaten angeben oder der Benutzer zu einem lokalen Workgroup-Benutzer gehört, müssen Sie UAC auf dem Host deaktivieren.
* Die benutzerdefinierten Plug-ins müssen auf dem Client-Host verfügbar sein, von dem aus der Add-Host-Vorgang ausgeführt wird.




== Allgemein

Wenn Sie iSCSI verwenden, muss der iSCSI-Dienst ausgeführt werden.



== Windows Hosts

* Sie müssen über einen Domänenbenutzer mit lokalen Administratorrechten mit lokalen Anmeldeberechtigungen auf dem Remote-Host verfügen.
* Wenn Sie Cluster-Nodes in SnapCenter verwalten, müssen Sie einen Benutzer mit Administratorrechten für alle Nodes im Cluster besitzen.




== Linux-Hosts

* Sie müssen die passwortbasierte SSH-Verbindung für den Root- oder nicht-Root-Benutzer aktiviert haben.
* Sie müssen Java 1.8 64-bit auf Ihrem Linux-Host installiert haben.
+
Wenn Sie Windows 2019 oder Windows 2016 für den SnapCenter-Server-Host verwenden, müssen Sie Java 1.8, 64-Bit installieren. Das Interoperabilitäts-Matrix-Tool (IMT) enthält aktuelle Informationen zu Anforderungen.

+
http://www.java.com/en/download/manual.jsp["Java-Downloads für alle Betriebssysteme"]

+
https://imt.netapp.com/matrix/imt.jsp?components=103047;&solution=1257&isHWU&src=IMT["NetApp Interoperabilitäts-Matrix-Tool"]

* Sie müssen sudo-Berechtigungen für den nicht-Root-Benutzer konfigurieren, um Zugriff auf mehrere Pfade zu ermöglichen. Fügen Sie die folgenden Zeilen zur Datei /etc/sudoers mit dem Dienstprogramm visudo Linux hinzu. Beispiel:
+
[listing]
----
Cmnd_Alias SCCMD = /opt/NetApp/snapcenter/scc/bin/scc <non_root_user> ALL=(ALL) NOPASSWD:SETENV: SCCMD
----
+
Non_root_user ist der Name des nicht-Root-Benutzers, den Sie erstellt haben.


